eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9999/eureka
spring:
  application:
    name: shopping
  cloud:
    config:
      uri: localhost:8888
  config:
    import: optional:configserver:http://localhost:8888