spring:
  cloud:
    config:
      uri: localhost:8888
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ordering
logging:
  level:
    com.github.rush: debug
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9999/eureka
